name: weatheranimationapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  smooth_page_indicator: ^0.1.4
  rxdart: ^0.22.6
  material_design_icons_flutter: ^3.4.4995


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.jpg
    - assets/images/london.jpg
    - assets/images/ahmedabad.jpeg
    - assets/images/California.jpeg
    - assets/images/Singapore.jpeg
    - assets/images/Canada.jpeg

  fonts:
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSansExtraBold
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf